version: '2'

services:
  ansible-head:
    build: ./ansible-head
    volumes:
      - '.:/ansible'
    
  web-server:
    build: ./server
    command: >
      /usr/sbin/sshd -D

  api-server:
    build: ./server
    command: >
      /usr/sbin/sshd -D
